#!/bin/sh

# We've placed the Dockerfile under docker/ so that the generically named
# hooks/ directory doesn't pollute the main directory.  Because we need to
# COPY the source into the container, we need to use some -f gymnastics to
# ensure that "COPY . /src" is referring to the repo root, not the directory
# that contains the Dockerfile.
# This script gets executed with a pwd of wherever the Dockerfile is.
DOCKER_IMAGE_NAME="wemap-osrm-frontend"
DOCKER_IMAGE_TAG="$([ ! -z "$1" ] && echo $1 || echo $(git rev-parse --short HEAD))"
cd docker
docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f Dockerfile ..
